name: form_bloc
description: "Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface. Async Validation, Progress, Dynamic fields, and more."
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  bloc: ^9.0.0
  rxdart: ^0.28.0
  equatable: ^2.0.3
  collection: ^1.15.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.26.3
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  fire_line_diff: ^1.5.3
  lints: ^6.0.0
